Establish `qa/` directory and `toolshed/git_squash-merge_ctk-next.sh` (#158)
* Establish qa/ directory and toolshed/git_squash-merge_ctk-next.sh

* Rough version of qa_cython-gen_linux.sh

* AUTOMATIC CHANGES cython-gen

* chmod 755 qa/helpers/git_merge_public_main.sh

* print flush=True

* ChatGPT-generated fix to break recursion.

* Manual trimming of "seen" code

* WIP snapshot qa/13.1.0/qa_bindings_linux.sh

* /usr/local/cuda-13.1_hacked/include/cuda.h with `struct CUstreamMemOpAtomicReductionParams_st` commented out.

* Disable cufile for now

* Update driver_cu_result_explanations.py using cuda_13.1.0_590.22_linux_kitpicks018.run

../../../../../toolshed/reformat_cuda_enums_as_py.py /usr/local/cuda-13.1_orig/include/cuda.h

* Update runtime_cuda_error_explanations.py using cuda_13.1.0_590.22_linux_kitpicks018.run

../../../../../toolshed/reformat_cuda_enums_as_py.py /usr/local/cuda-13.1_orig/include/driver_types.h

* Silence ruff warning (fixes oversight in bd3cfd3b63fc606d3c6340b8b414a715c8d594e8)

* DBG WIP parse_headers_ONLY pprint

* Restore original discoverMembers

* Break the infinite recursion in discoverMembers very specifically.

* regenerate.py again with both hacks undone

* Archiving debug changes: found_types.extend(...)

* Revert "Archiving debug changes: found_types.extend(...)"

This reverts commit 1d9ae726895551dcdeb0cdfddc5dbc4c9b125767.

* FIX: Add CUstreamMemOpAtomicReductionParams_st to special-case list for Struct._isAnonymous assignment.

* Add back found_types.extend CUstreamAtomicReductionDataType_enum

* Revert "Break the infinite recursion in discoverMembers very specifically."

This reverts commit 9f67aee46ee41a765e671f3987bdbcc7efae5573.

* Revert "Restore original discoverMembers"

This reverts commit 0f90cda57d6b5bf0fde801015662a8419727bad0.

* Remove qa_cython-gen_linux.sh

* export CUDA_PYTHON_PARALLEL_LEVEL="$(nproc)"

* More general skip cufile

* Handle pyglet.display.xlib.NoSuchDisplayException in test_graphics_apis.py::test_graphics_api_smoketest

============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-8.4.2, pluggy-1.6.0 -- /wrk/bld04/ctk-next/TestVenv/bin/python
cachedir: .pytest_cache
benchmark: 5.1.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /wrk/bld04/ctk-next/cuda_bindings/tests
configfile: pytest.ini
plugins: benchmark-5.1.0
collecting ... collected 2 items

tests/test_graphics_apis.py::test_graphics_api_smoketest FAILED
tests/test_graphics_apis.py::test_cuda_register_image_invalid PASSED

=================================== FAILURES ===================================
_________________________ test_graphics_api_smoketest __________________________

self = <pyglet._ModuleProxy object at 0x736370d73680>, name = 'Texture'

    def __getattr__(self, name: str): # noqa: ANN204
        try:
>           return getattr(self._module, name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
E           AttributeError: 'NoneType' object has no attribute 'Texture'

../TestVenv/lib/python3.12/site-packages/pyglet/__init__.py:439: AttributeError

During handling of the above exception, another exception occurred:

    def test_graphics_api_smoketest():
        # Due to lazy importing in pyglet, pytest.importorskip doesn't work
        try:
            import pyglet

>           tex = pyglet.image.Texture.create(512, 512)
                  ^^^^^^^^^^^^^^^^^^^^

tests/test_graphics_apis.py:13:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../TestVenv/lib/python3.12/site-packages/pyglet/__init__.py:445: in __getattr__
    __import__(import_name)
../TestVenv/lib/python3.12/site-packages/pyglet/image/__init__.py:106: in <module>
    from pyglet.gl import (
../TestVenv/lib/python3.12/site-packages/pyglet/gl/__init__.py:205: in <module>
    import pyglet.window  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^
../TestVenv/lib/python3.12/site-packages/pyglet/window/__init__.py:1904: in <module>
    gl._create_shadow_window()  # noqa: SLF001
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
../TestVenv/lib/python3.12/site-packages/pyglet/gl/__init__.py:179: in _create_shadow_window
    _shadow_window = ShadowWindow()
                     ^^^^^^^^^^^^^^
../TestVenv/lib/python3.12/site-packages/pyglet/gl/__init__.py:168: in __init__
    super().__init__(width=1, height=1, visible=False)
../TestVenv/lib/python3.12/site-packages/pyglet/window/xlib/__init__.py:167: in __init__
    super().__init__(*args, **kwargs)
../TestVenv/lib/python3.12/site-packages/pyglet/window/__init__.py:508: in __init__
    display = pyglet.display.get_display()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../TestVenv/lib/python3.12/site-packages/pyglet/display/__init__.py:77: in get_display
    return Display()
           ^^^^^^^^^
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pyglet.display.xlib.XlibDisplay object at 0x7363707728a0>, name = None
x_screen = 0

    def __init__(self, name=None, x_screen=None):
        self._screens = []

        if x_screen is None:
            x_screen = 0

        if isinstance(name, str):
            name = c_char_p(name.encode('ascii'))

        self._display = xlib.XOpenDisplay(name)
        if not self._display:
>           raise NoSuchDisplayException(f'Cannot connect to "{name}"')
E           pyglet.display.xlib.NoSuchDisplayException: Cannot connect to "None"

../TestVenv/lib/python3.12/site-packages/pyglet/display/xlib.py:102: NoSuchDisplayException
=========================== short test summary info ============================
FAILED tests/test_graphics_apis.py::test_graphics_api_smoketest - pyglet.disp...
========================= 1 failed, 1 passed in 3.68s ==========================

* qa_bindings_linux.sh: go back to set +e

* pytest_report_header: initial current working directory

* Revert "pytest_report_header: initial current working directory"

This reverts commit f5c260874782e710fe1be6c2b67c2054adbecb6a.

* Add five "CURRENTLY EXCLUDED FROM CTK 13.1 TESTING" in cuda_core/tests/memory_ipc/test_memory_ipc.py, test_serialize.py

* Add two @pytest.mark.skip() in cuda_core/tests/memory_ipc/test_errors.py

* Change "CURRENTLY EXCLUDED FROM CTK 13.1 TESTING" → "TODO(CTK-NEXT-13010): CURRENTLY EXCLUDED FROM TESTING"

* Add comment: TODO(CTK-NEXT-13010): enable cufile

* Remove debug code, add TODO(CTK-NEXT-13010) for found_types.append("CUstreamAtomicReductionDataType_enum")

* Add qa_bindings_linux_build.sh, qa_bindings_linux_tests.sh, remove qa_bindings_linux.sh, qa_bindings_win.cmd

* Add qa_bindings_windows_build,tests.cmd files

* cuda_bindings/tests/test_graphics_apis.py: handle `os.environ.get("DISPLAY") is None`

* Exclude 3 failing tests for now (Linux x86_64 with more than 1 GPU)